{
  "openapi": "3.0.0",
  "info": {
    "title": "Qualified Teachers API",
    "version": "v2"
  },
  "paths": {
    "/v2/teachers/{trn}/itt-outcome": {
      "put": {
        "tags": [
          "IttOutcome"
        ],
        "summary": "Set ITT outcome",
        "description": "Sets the ITT outcome for a teacher",
        "operationId": "SetIttOutcome",
        "parameters": [
          {
            "name": "trn",
            "in": "path",
            "required": true,
            "description": "The TRN of the teacher to set ITT outcome for.",
            "schema": {
              "type": "string"
            },
            "x-position": 2
          },
          {
            "name": "birthdate",
            "in": "query",
            "description": "DoB of teacher",
            "schema": {
              "type": "string",
              "format": "date",
              "nullable": true
            },
            "x-position": 3
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SetIttOutcomeRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SetIttOutcomeResponse"
                },
                "example": {
                  "trn": "1234567",
                  "qtsDate": "2021-12-23"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "409": {
            "description": "Conflict",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "429": {
            "$ref": "#/components/responses/429",
            "description": "Too Many Requests"
          }
        }
      }
    },
    "/v2/itt-providers": {
      "get": {
        "tags": [
          "IttProviders"
        ],
        "summary": "Get ITT Providers",
        "description": "Gets the list of ITT providers",
        "operationId": "GetIttProviders",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetIttProvidersResponse"
                }
              }
            }
          },
          "429": {
            "$ref": "#/components/responses/429",
            "description": "Too Many Requests"
          }
        }
      }
    },
    "/v2/npq-qualifications": {
      "put": {
        "tags": [
          "NpqQualifications"
        ],
        "summary": "Set NPQ qualification",
        "description": "Sets the NPQ qualification for a teacher and qualification type",
        "operationId": "SetNpqQualification",
        "parameters": [
          {
            "name": "trn",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 2
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SetNpqQualificationRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "description": "Bad Request"
          },
          "429": {
            "$ref": "#/components/responses/429",
            "description": "Too Many Requests"
          }
        }
      }
    },
    "/v2/teachers/find": {
      "get": {
        "tags": [
          "Teachers"
        ],
        "summary": "Find teachers",
        "description": "Returns teachers matching the specified criteria",
        "operationId": "FindTeachers",
        "parameters": [
          {
            "name": "firstName",
            "in": "query",
            "description": "First name of person",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          },
          {
            "name": "lastName",
            "in": "query",
            "description": "Last name of person",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 2
          },
          {
            "name": "previousFirstName",
            "in": "query",
            "description": "Previous first name of person",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 3
          },
          {
            "name": "previousLastName",
            "in": "query",
            "description": "Previous last name of person",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 4
          },
          {
            "name": "dateOfBirth",
            "in": "query",
            "description": "Date of birth of person",
            "schema": {
              "type": "string",
              "format": "date",
              "nullable": true
            },
            "x-position": 5
          },
          {
            "name": "nationalInsuranceNumber",
            "in": "query",
            "description": "National insurance number of person",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 6
          },
          {
            "name": "ittProviderName",
            "in": "query",
            "description": "Name of teacher training provider",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 7
          },
          {
            "name": "ittProviderUkprn",
            "in": "query",
            "description": "UKPRN of teacher training provider",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 8
          },
          {
            "name": "emailAddress",
            "in": "query",
            "description": "Email of person",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 9
          },
          {
            "name": "trn",
            "in": "query",
            "description": "TRN of person",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 10
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FindTeachersResponse"
                }
              }
            }
          },
          "429": {
            "$ref": "#/components/responses/429",
            "description": "Too Many Requests"
          }
        }
      }
    },
    "/v2/teachers/{trn}": {
      "get": {
        "tags": [
          "Teachers"
        ],
        "summary": "Get teacher",
        "description": "Gets an individual teacher by their TRN",
        "operationId": "GetTeacher",
        "parameters": [
          {
            "name": "trn",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "x-position": 1
          },
          {
            "name": "includeInactive",
            "in": "query",
            "schema": {
              "type": "boolean",
              "nullable": true
            },
            "x-position": 2
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetTeacherResponse"
                }
              }
            }
          },
          "429": {
            "$ref": "#/components/responses/429",
            "description": "Too Many Requests"
          }
        }
      }
    },
    "/v2/teachers/update/{trn}": {
      "patch": {
        "tags": [
          "Teachers"
        ],
        "summary": "Update teacher",
        "description": "Updates a teacher",
        "operationId": "UpdateTeacher",
        "parameters": [
          {
            "name": "trn",
            "in": "path",
            "required": true,
            "description": "The TRN of the teacher to update",
            "schema": {
              "type": "string"
            },
            "x-position": 2
          },
          {
            "name": "birthdate",
            "in": "query",
            "description": "DoB of teacher",
            "schema": {
              "type": "string",
              "format": "date",
              "nullable": true
            },
            "x-position": 3
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateTeacherRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "204": {
            "description": "No Content"
          },
          "429": {
            "$ref": "#/components/responses/429",
            "description": "Too Many Requests"
          }
        }
      }
    },
    "/v2/trn-requests/{requestId}": {
      "get": {
        "tags": [
          "TrnRequests"
        ],
        "summary": "Get TRN request",
        "description": "Gets a TRN request and the associated teacher's TRN",
        "operationId": "GetTrnRequest",
        "parameters": [
          {
            "name": "requestId",
            "in": "path",
            "required": true,
            "description": "The unique ID the TRN request was created with.",
            "schema": {
              "type": "string"
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TrnRequestInfo"
                },
                "example": {
                  "requestId": "72888c5d-db14-4222-829b-7db9c2ec0dc3",
                  "status": "Completed",
                  "trn": "1234567",
                  "potentialDuplicate": false,
                  "qtsDate": null
                }
              }
            }
          },
          "404": {
            "description": "Not Found"
          },
          "429": {
            "$ref": "#/components/responses/429",
            "description": "Too Many Requests"
          }
        }
      },
      "put": {
        "tags": [
          "TrnRequests"
        ],
        "summary": "Get or create TRN request",
        "description": "Gets or creates a request for a TRN",
        "operationId": "GetOrCreateTrnRequest",
        "parameters": [
          {
            "name": "requestId",
            "in": "path",
            "required": true,
            "description": "A unique ID that represents this request. If a request has already been created with this ID then that existing record's result is returned.",
            "schema": {
              "type": "string"
            },
            "x-position": 2
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/GetOrCreateTrnRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TrnRequestInfo"
                },
                "example": {
                  "requestId": "72888c5d-db14-4222-829b-7db9c2ec0dc3",
                  "status": "Completed",
                  "trn": "1234567",
                  "potentialDuplicate": false,
                  "qtsDate": null
                }
              }
            }
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TrnRequestInfo"
                },
                "example": {
                  "requestId": "72888c5d-db14-4222-829b-7db9c2ec0dc3",
                  "status": "Completed",
                  "trn": "1234567",
                  "potentialDuplicate": false,
                  "qtsDate": null
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "429": {
            "$ref": "#/components/responses/429",
            "description": "Too Many Requests"
          }
        }
      }
    },
    "/v2/unlock-teacher/{teacherId}": {
      "put": {
        "tags": [
          "UnlockTeacher"
        ],
        "summary": "Unlock teacher",
        "description": "Unlocks the teacher record allowing the teacher to sign in to the portals",
        "operationId": "UnlockTeacher",
        "parameters": [
          {
            "name": "teacherId",
            "in": "path",
            "required": true,
            "description": "The ID of the teacher record to unlock",
            "schema": {
              "type": "string",
              "format": "guid"
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UnlockTeacherResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found"
          },
          "429": {
            "$ref": "#/components/responses/429",
            "description": "Too Many Requests"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "SetIttOutcomeResponse": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "trn": {
            "type": "string"
          },
          "qtsDate": {
            "type": "string",
            "format": "date",
            "nullable": true
          }
        }
      },
      "ProblemDetails": {
        "type": "object",
        "additionalProperties": {
          "nullable": true
        },
        "properties": {
          "type": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "nullable": true
          },
          "status": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "detail": {
            "type": "string",
            "nullable": true
          },
          "instance": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "SetIttOutcomeRequest": {
        "type": "object",
        "example": {
          "ittProviderUkprn": "1001234",
          "outcome": "Pass",
          "assessmentDate": "2021-12-22"
        },
        "additionalProperties": false,
        "required": [
          "ittProviderUkprn",
          "outcome"
        ],
        "properties": {
          "ittProviderUkprn": {
            "type": "string",
            "description": "The UKPRN of the ITT provider.",
            "minLength": 1
          },
          "outcome": {
            "$ref": "#/components/schemas/IttOutcome"
          },
          "assessmentDate": {
            "type": "string",
            "description": "The assessment date for a Pass outcome.",
            "format": "date",
            "nullable": true
          }
        }
      },
      "IttOutcome": {
        "type": "string",
        "description": "",
        "x-enumNames": [
          "Pass",
          "Fail",
          "Deferred",
          "Approved"
        ],
        "enum": [
          "Pass",
          "Fail",
          "Deferred",
          "Approved"
        ]
      },
      "GetIttProvidersResponse": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "ittProviders": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/IttProviderInfo"
            }
          }
        }
      },
      "IttProviderInfo": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "ukprn": {
            "type": "string"
          },
          "providerName": {
            "type": "string"
          }
        }
      },
      "SetNpqQualificationRequest": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "completionDate",
          "trn",
          "qualificationType"
        ],
        "properties": {
          "completionDate": {
            "type": "string",
            "format": "date",
            "minLength": 1
          },
          "trn": {
            "type": "string",
            "minLength": 1
          },
          "qualificationType": {
            "$ref": "#/components/schemas/QualificationType"
          }
        }
      },
      "QualificationType": {
        "type": "string",
        "description": "",
        "x-enumNames": [
          "NPQH",
          "NPQSL",
          "NPQLTD"
        ],
        "enum": [
          "NPQH",
          "NPQSL",
          "NPQLTD"
        ]
      },
      "FindTeachersResponse": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "results": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/FindTeacherResult"
            }
          }
        }
      },
      "FindTeacherResult": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "trn": {
            "type": "string"
          },
          "emailAddresses": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "dateOfBirth": {
            "type": "string",
            "format": "date",
            "nullable": true
          },
          "nationalInsuranceNumber": {
            "type": "string",
            "nullable": true
          },
          "uid": {
            "type": "string"
          },
          "hasActiveSanctions": {
            "type": "boolean"
          }
        }
      },
      "GetTeacherResponse": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "trn": {
            "type": "string",
            "nullable": true
          },
          "firstName": {
            "type": "string",
            "nullable": true
          },
          "lastName": {
            "type": "string",
            "nullable": true
          },
          "middleName": {
            "type": "string",
            "nullable": true
          },
          "dateOfBirth": {
            "type": "string",
            "format": "date",
            "nullable": true
          },
          "nationalInsuranceNumber": {
            "type": "string",
            "nullable": true
          },
          "hasActiveSanctions": {
            "type": "boolean"
          },
          "qtsDate": {
            "type": "string",
            "format": "date",
            "nullable": true
          },
          "eytsDate": {
            "type": "string",
            "format": "date",
            "nullable": true
          },
          "husId": {
            "type": "string",
            "nullable": true
          },
          "earlyYearsStatus": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/GetTeacherResponseEarlyYearsStatus"
              }
            ]
          },
          "initialTeacherTraining": {
            "type": "array",
            "nullable": true,
            "items": {
              "$ref": "#/components/schemas/GetTeacherResponseInitialTeacherTraining"
            }
          }
        }
      },
      "GetTeacherResponseEarlyYearsStatus": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "value": {
            "type": "string",
            "nullable": true
          },
          "name": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "GetTeacherResponseInitialTeacherTraining": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "programmeStartDate": {
            "type": "string",
            "format": "date",
            "nullable": true
          },
          "programmeEndDate": {
            "type": "string",
            "format": "date",
            "nullable": true
          },
          "programmeType": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/IttProgrammeType"
              }
            ]
          },
          "result": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/IttOutcome"
              }
            ]
          },
          "provider": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/GetTeacherResponseInitialTeacherTrainingProvider"
              }
            ]
          },
          "husId": {
            "type": "string",
            "nullable": true
          },
          "active": {
            "type": "boolean"
          }
        }
      },
      "IttProgrammeType": {
        "type": "string",
        "description": ""
      },
      "GetTeacherResponseInitialTeacherTrainingProvider": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "ukprn": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "UpdateTeacherRequest": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "initialTeacherTraining",
          "qualification"
        ],
        "properties": {
          "initialTeacherTraining": {
            "$ref": "#/components/schemas/UpdateTeacherRequestInitialTeacherTraining"
          },
          "qualification": {
            "$ref": "#/components/schemas/UpdateTeacherRequestQualification"
          },
          "husId": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "UpdateTeacherRequestInitialTeacherTraining": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "providerUkprn",
          "programmeStartDate",
          "programmeEndDate",
          "programmeType"
        ],
        "properties": {
          "providerUkprn": {
            "type": "string",
            "minLength": 1
          },
          "programmeStartDate": {
            "type": "string",
            "format": "date",
            "minLength": 1
          },
          "programmeEndDate": {
            "type": "string",
            "format": "date",
            "minLength": 1
          },
          "programmeType": {
            "$ref": "#/components/schemas/IttProgrammeType"
          },
          "subject1": {
            "type": "string",
            "nullable": true
          },
          "subject2": {
            "type": "string",
            "nullable": true
          },
          "subject3": {
            "type": "string",
            "nullable": true
          },
          "ageRangeFrom": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "ageRangeTo": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "ittQualificationType": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/IttQualificationType"
              }
            ]
          },
          "ittQualificationAim": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/IttQualificationAim"
              }
            ]
          },
          "trainingCountryCode": {
            "type": "string",
            "nullable": true
          },
          "outcome": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/IttOutcome"
              }
            ]
          }
        }
      },
      "IttQualificationType": {
        "type": "string",
        "description": "",
        "x-enumNames": [
          "BEd",
          "BEdHons",
          "BScHons",
          "BAHons",
          "BEngHons_Education",
          "MastersNotByResearch"
        ],
        "enum": [
          "BEd",
          "BEdHons",
          "BScHons",
          "BAHons",
          "BEngHons_Education",
          "MastersNotByResearch"
        ]
      },
      "IttQualificationAim": {
        "type": "string",
        "description": ""
      },
      "UpdateTeacherRequestQualification": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "providerUkprn": {
            "type": "string",
            "nullable": true
          },
          "countryCode": {
            "type": "string",
            "nullable": true
          },
          "subject": {
            "type": "string",
            "nullable": true
          },
          "subject2": {
            "type": "string",
            "nullable": true
          },
          "subject3": {
            "type": "string",
            "nullable": true
          },
          "class": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/ClassDivision"
              }
            ]
          },
          "date": {
            "type": "string",
            "format": "date",
            "nullable": true
          },
          "heQualificationType": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/HeQualificationType"
              }
            ]
          }
        }
      },
      "ClassDivision": {
        "type": "string",
        "description": ""
      },
      "HeQualificationType": {
        "type": "string",
        "description": "",
        "x-enumNames": [
          "BEd",
          "BEdHons",
          "BScHons_Education",
          "BAHons_Education",
          "BachelorOfDentalSurgery"
        ],
        "enum": [
          "BEd",
          "BEdHons",
          "BScHons_Education",
          "BAHons_Education",
          "BachelorOfDentalSurgery"
        ]
      },
      "TrnRequestInfo": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "requestId": {
            "type": "string"
          },
          "status": {
            "$ref": "#/components/schemas/TrnRequestStatus"
          },
          "trn": {
            "type": "string",
            "nullable": true
          },
          "potentialDuplicate": {
            "type": "boolean"
          },
          "qtsDate": {
            "type": "string",
            "format": "date",
            "nullable": true
          }
        }
      },
      "TrnRequestStatus": {
        "type": "string",
        "description": "",
        "x-enumNames": [
          "Completed"
        ],
        "enum": [
          "Completed"
        ]
      },
      "GetOrCreateTrnRequest": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "firstName",
          "lastName",
          "birthDate",
          "genderCode",
          "initialTeacherTraining",
          "qualification"
        ],
        "properties": {
          "firstName": {
            "type": "string",
            "minLength": 1
          },
          "middleName": {
            "type": "string",
            "nullable": true
          },
          "lastName": {
            "type": "string",
            "minLength": 1
          },
          "birthDate": {
            "type": "string",
            "format": "date",
            "minLength": 1
          },
          "emailAddress": {
            "type": "string",
            "nullable": true
          },
          "address": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/GetOrCreateTrnRequestAddress"
              }
            ]
          },
          "genderCode": {
            "$ref": "#/components/schemas/Gender"
          },
          "initialTeacherTraining": {
            "$ref": "#/components/schemas/GetOrCreateTrnRequestInitialTeacherTraining"
          },
          "qualification": {
            "$ref": "#/components/schemas/GetOrCreateTrnRequestQualification"
          },
          "husId": {
            "type": "string",
            "nullable": true
          },
          "teacherType": {
            "$ref": "#/components/schemas/CreateTeacherType"
          },
          "recognitionRoute": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/CreateTeacherRecognitionRoute"
              }
            ]
          },
          "qtsDate": {
            "type": "string",
            "format": "date",
            "nullable": true
          },
          "inductionRequired": {
            "type": "boolean",
            "nullable": true
          },
          "identityUserId": {
            "type": "string",
            "format": "guid",
            "nullable": true
          },
          "underNewOverseasRegulations": {
            "type": "boolean",
            "nullable": true
          }
        }
      },
      "GetOrCreateTrnRequestAddress": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "addressLine1": {
            "type": "string",
            "nullable": true
          },
          "addressLine2": {
            "type": "string",
            "nullable": true
          },
          "addressLine3": {
            "type": "string",
            "nullable": true
          },
          "city": {
            "type": "string",
            "nullable": true
          },
          "postalCode": {
            "type": "string",
            "nullable": true
          },
          "country": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "Gender": {
        "type": "string",
        "description": "",
        "x-enumNames": [
          "Male",
          "Female"
        ],
        "enum": [
          "Male",
          "Female"
        ]
      },
      "GetOrCreateTrnRequestInitialTeacherTraining": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "providerUkprn",
          "programmeStartDate",
          "programmeEndDate",
          "programmeType"
        ],
        "properties": {
          "providerUkprn": {
            "type": "string",
            "minLength": 1
          },
          "programmeStartDate": {
            "type": "string",
            "format": "date",
            "minLength": 1
          },
          "programmeEndDate": {
            "type": "string",
            "format": "date",
            "minLength": 1
          },
          "programmeType": {
            "$ref": "#/components/schemas/IttProgrammeType"
          },
          "subject1": {
            "type": "string",
            "nullable": true
          },
          "subject2": {
            "type": "string",
            "nullable": true
          },
          "subject3": {
            "type": "string",
            "nullable": true
          },
          "ageRangeFrom": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "ageRangeTo": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "ittQualificationType": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/IttQualificationType"
              }
            ]
          },
          "ittQualificationAim": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/IttQualificationAim"
              }
            ]
          },
          "trainingCountryCode": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "GetOrCreateTrnRequestQualification": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "providerUkprn": {
            "type": "string",
            "nullable": true
          },
          "countryCode": {
            "type": "string",
            "nullable": true
          },
          "subject": {
            "type": "string",
            "nullable": true
          },
          "subject2": {
            "type": "string",
            "nullable": true
          },
          "subject3": {
            "type": "string",
            "nullable": true
          },
          "class": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/ClassDivision"
              }
            ]
          },
          "date": {
            "type": "string",
            "format": "date",
            "nullable": true
          },
          "heQualificationType": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/HeQualificationType"
              }
            ]
          }
        }
      },
      "CreateTeacherType": {
        "type": "string",
        "description": "",
        "x-enumNames": [
          "OverseasQualifiedTeacher"
        ],
        "enum": [
          "OverseasQualifiedTeacher"
        ]
      },
      "CreateTeacherRecognitionRoute": {
        "type": "string",
        "description": "",
        "x-enumNames": [
          "Scotland",
          "NorthernIreland",
          "OverseasTrainedTeachers"
        ],
        "enum": [
          "Scotland",
          "NorthernIreland",
          "OverseasTrainedTeachers"
        ]
      },
      "UnlockTeacherResponse": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "hasBeenUnlocked": {
            "type": "boolean",
            "description": "Whether the account has been unlocked"
          }
        }
      }
    },
    "responses": {
      "429": {
        "description": "Too Many Requests",
        "content": {
          "application/problem+json": {
            "schema": {
              "$ref": "#/components/schemas/ProblemDetails"
            }
          }
        }
      }
    },
    "securitySchemes": {
      "ApiKey": {
        "type": "http",
        "name": "Authorization",
        "in": "header",
        "scheme": "Bearer"
      }
    }
  },
  "security": [
    {
      "ApiKey": []
    }
  ]
}